### ISSUE TITLE
Add H2020 funding note

### ISSUE THREAD

**Issue by dkastl** [consento-org/consento-website#10]
Add the following sentence to the project website:

> This project has received funding from the European Union’s Horizon 2020
> research and innovation programme within the framework of the LEDGER
> Project funded under grant agreement No825268.

Together with the EU emblem and LEDGER logo:

![Screenshot from 2020-01-31 12-25-41](https://user-images.githubusercontent.com/227762/73510231-d4ec7880-4424-11ea-836d-85d5c9167f98.png)
(this is just a screenshot, use original logos with appropriate quality)

**Comment by dkastl** [comment]
@Torgian , would be able to assign this to you, if you accept the invitation to the Consento Github group.

**Comment by Torgian** [comment]
Ok I will add this and also look for the email with the invitation. I will be doing most of my work today this afternoon and evening

**Comment by dkastl** [comment]
Here is an example on the mobile repo: https://github.com/consento-org/mobile/pull/44

**Comment by Torgian** [comment]
@dkastl  Can you send the invite to me again? I can’t seem to find it in my inbox or spam folders.

**Comment by Torgian** [comment]
FYI, I have updated the server with the note and images.
