### ISSUE TITLE
404 page broken

### ISSUE THREAD

**Issue by martinheidegger** [consento-org/consento-website#101]
The 404 page of the website is in disarray ↓ but what is worse is that the pages are not setup for dat or netlify; see https://github.com/consento-org/dat-ssg/issues/1

<img width="1319" alt="Screen Shot 2020-03-05 at 05 00 00" src="https://user-images.githubusercontent.com/914122/75918407-02529900-5e9f-11ea-9744-3f688b6fc557.png">

**Comment by Tannybunny** [comment]
Should I make a quick Illustration for that? :)

**Comment by martinheidegger** [comment]
@Tannybunny always welcome 😉

**Comment by martinheidegger** [comment]
dat-ssg added support for 404 files and the server is updated. Can be updated in the ghost cms.
