### ISSUE TITLE
Navigation bar styling

### ISSUE THREAD

**Issue by dkastl** [consento-org/consento-website#11]
Here is a list of immprovements for the navigation bar:

- [x] On lager screens the current navigation bar does not look good, because the content and footer have a fix width and the navigation bar is 100% of the screen:

![Screenshot from 2020-02-01 23-35-08](https://user-images.githubusercontent.com/227762/73593841-97363f80-454b-11ea-89aa-72401c87c480.png)

- [x] The spaces between navigation bar items do not have to be too big. The following looks better to me in terms of font size and spacing:

![Screenshot from 2020-02-01 23-37-09](https://user-images.githubusercontent.com/227762/73593887-e3817f80-454b-11ea-8399-b9a1e93fcb44.png)

- [x] Let's not collapse the navigation without any padding

![Screenshot from 2020-02-01 23-39-02](https://user-images.githubusercontent.com/227762/73593906-2d6a6580-454c-11ea-8320-2d472a0041f7.png)

- [x] Menu items can be visible longer

![Screenshot from 2020-02-01 23-40-44](https://user-images.githubusercontent.com/227762/73593914-512dab80-454c-11ea-9205-36cdddd25560.png)

- [x] The logo enlarges when mouse over, but it also hides part of the left side of the logo

![Screenshot from 2020-02-01 23-41-39](https://user-images.githubusercontent.com/227762/73593928-7cb09600-454c-11ea-9762-538e3bc8d971.png)

**Comment by Torgian** [comment]
I'm working on the other issues right now, but the following issue:

``` On lager screens the current navigation bar does not look good, because the content and footer have a fix width and the navigation bar is 100% of the screen:```

I will fix this last, since it will require the most testing.

**Comment by marcchataigner-zz** [comment]
Update proposal: 

The font for `about`, `supporters`, `team` and `download` switch: 
- [ ] from  `bold` >  `medium` 
- [ ] remove `smallcap`

**Comment by marcchataigner-zz** [comment]
Proposal.  @Torgian would that help? 

![Navbar specifications](https://user-images.githubusercontent.com/3974900/73620622-19bb1e00-4676-11ea-8270-8804cac26180.png)

**Comment by Torgian** [comment]
Daniel already stated he didn’t want the Navbar to collapse while scrolling, so I removed that functionality.

**Comment by Torgian** [comment]
> On larger screens the current navigation bar does not look good, because the content and footer have a fix width and the navigation bar is 100% of the screen:
Screenshot from 2020-02-01 23-35-08


This will be finished after other issues are taken care of.

**Comment by Torgian** [comment]
I have two screenshots.  Which style of nav bar do you prefer?

Here i have a screenshot where the max width of the nav-bar and the footer is just slightly larger than the containers in the rest of the page.

<img width="893" alt="Screen Shot 2020-02-03 at 4 55 04 PM" src="https://user-images.githubusercontent.com/8596793/73639149-c6ad8f00-46a6-11ea-92d1-f1528086d754.png">

The second one is where the nav bar and footer matches the interior.

<img width="889" alt="Screen Shot 2020-02-03 at 4 57 13 PM" src="https://user-images.githubusercontent.com/8596793/73639203-dc22b900-46a6-11ea-95f6-6ab8fe19006a.png">

**Comment by Torgian** [comment]
From feedback with marc and Tanja, I will make it match the second screenshot. Funding text is fixed as well. Closing issue.
