### ISSUE TITLE
Font sizes

### ISSUE THREAD

**Issue by marcchataigner-zz** [consento-org/consento-website#15]
could it be possible to make a try to downsize button label and body fonts?

Button label: 24pt > 21pt
Body: 21pt > 18pt

**Comment by Torgian** [comment]
Let's wait until after the redesign before changing fonts. Mobile / tablet redesign might change the look a bit.

**Comment by Torgian** [comment]
Let me know if you still want to change some of the font-sizes after looking at the mobile / tablet redesign.

**Comment by Torgian** [comment]
I've replaced the font sizes, etc, with the one in @marcchataigner design. Please reopen and comment if this continues to be an issue.
