### ISSUE TITLE
Implemented new illustrations

### ISSUE THREAD

**Issue by marcchataigner-zz** [consento-org/consento-website#16]
- [ ] hero
- [ ] roadmap
- [ ] usecase 1 & 2
- [ ] NGI logo in color and in white (for footer)

**Comment by Torgian** [comment]
Please send me a link to the new images

**Comment by Tannybunny** [comment]
I pushed them to github .. (i think... let me know if it didnt work ^^)

**Comment by Torgian** [comment]
Added new images, closing.
