### ISSUE TITLE
Supporter page

### ISSUE THREAD

**Issue by marcchataigner-zz** [consento-org/consento-website#20]
Supporter page: https://zpl.io/VDw9lA3

- [x] add 'consento receive funding part'
- [x] Here could be a way to improve the spacing (cf. PNG)

![Screen Shot 2020-02-03 at 12 16 09](https://user-images.githubusercontent.com/3974900/73623196-7d961480-467f-11ea-9c94-31f228222ad9.png)

![Screen Shot 2020-02-03 at 12 16 16](https://user-images.githubusercontent.com/3974900/73623235-9dc5d380-467f-11ea-8372-79a0dd4d6ced.png)

**Comment by Torgian** [comment]
Before we do a bunch of styling changes for these other pages, remember that these are dynamically created by Ghost. (About, Supporters, Team, Credits)

I can change some styling, but these will need to be tested on the server. So we should keep styling changes minimal.

**Comment by Torgian** [comment]
I will work on this and fix the spacing issues tonight on all of the dynamically created pages.

**Comment by Torgian** [comment]
Consento received funding has already been added a few days ago.

**Comment by Torgian** [comment]
Added code to fix this styling. I will need to upload to server to test, but doing so in the inspector looks good. Made the changes and will update server soon

**Comment by Torgian** [comment]
Fixed, closing.
