### ISSUE TITLE
"How it works" images are blurred

### ISSUE THREAD

**Issue by Tannybunny** [consento-org/consento-website#21]
<img width="1093" alt="Screen Shot 2020-02-04 at 15 54 41" src="https://user-images.githubusercontent.com/51223963/73721171-00de6580-4767-11ea-8bd6-4e6df5d81438.png">

The images are not sharp - I don't know if it's due to low resolution or changing the size via HTML? I pushed higher resolutions of these images to git, in case they are needed

**Comment by Torgian** [comment]
Ahh, I know why this is; early in development, we needed to reduce the size of all the images; in turn, this has made the quality drop. I will grab your higher resolution versions and compare their sizes, and see if I can find a middle ground ( if needed )

**Comment by codingjustahobby** [comment]
I don't really know , but I have a guess and according to what I see , I think my guess is accurate . If you know python then you can check my repository on blurring images , it works.  If you don't python I have explained my algorithm in a txt file

**Comment by codingjustahobby** [comment]
That is how I think images are being blurred

**Comment by Torgian** [comment]
Replaced images. Doesn't look blurry on large screens. Closing.

**Comment by Tannybunny** [comment]
The images are still blurred - but I guess the problem is the mac retina display. So in ordner to have sharp images on mac (iMac, macbook pro) we need to provide an image with double the size probably. OR: we use svgs. Second option might be better? Or are there any concerns with using svgs?

**Comment by Torgian** [comment]
I think the resolution might be too low for the size we want. I will switch to a higher resolution version. I didn’t really see it before, but I can see it now. 

I am working on CTI at the moment, but will get back to this later today.

**Comment by martinheidegger** [comment]
@Torgian you do not need to update the issues with estimates, just upload the files.

About this issue, you need to prepare and use the images in multiple resolutions, similar like we do in the mobile app, aside from that it a reduction of size particularly of this kind of image is easiest achieve using the Mac tool [ImageAlpha](https://pngmini.com/)

**Comment by martinheidegger** [comment]
@Tannybunny It might be a good idea to prepare a .sketch file that contains all files to export in all the given resolutions.

**Comment by Torgian** [comment]
Yes, I used image Alpha before for size reduction. But, I’m wondering, is it really ok to upload several resolutions of the same image? 

Wouldn’t the user need to download all those images when they visit the site? I assume that they’ll be cached for future visits, but I’m wondering if it’s better to just upload one image that can be used for all sizes, or upload multiple images of differing resolutions. 

This is why I’ve avoided uploading three different image sizes. Otherwise, if you think it’s fine, then I’ll go ahead and do that, after I process them through imagealpha to reduce size.

**Comment by Torgian** [comment]
@martinheidegger I actually already have all the images in three different sizes ( Zepplin already provides them )

**Comment by martinheidegger** [comment]
> Wouldn’t the user need to download all those images when they visit the site? I assume that they’ll be cached for future visits, but I’m wondering if it’s better to just upload one image that can be used for all sizes, or upload multiple images of differing resolutions.

[Responsive Images](https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images) get only downloaded when the size is required, not all sizes will be downloaded, browsers are clever like that.

**Comment by martinheidegger** [comment]
> I actually already have all the images in three different sizes ( Zepplin already provides them )

It would still be good to have the sketch file in the same location as the other source code.

**Comment by Torgian** [comment]
> > Wouldn’t the user need to download all those images when they visit the site? I assume that they’ll be cached for future visits, but I’m wondering if it’s better to just upload one image that can be used for all sizes, or upload multiple images of differing resolutions.
> 
> [Responsive Images] get only downloaded when the size is required, not all sizes will be downloaded, browsers are clever like that.

Ahh ok, I was unaware. Thank you. I'll read the link you sent too.

**Comment by Tannybunny** [comment]
@martinheidegger ok I can prepare the sketch file. How about using SVG though ?

**Comment by martinheidegger** [comment]
@Tannybunny the exported format may be `.svg`, but it is still a good idea original file as `.sketch` at hand, in order for others to be able to make changes to it.

**Comment by martinheidegger** [comment]
New images are offered in #63

**Comment by Torgian** [comment]
#63 has been merged and images look clear. However, would it be better to use the .svgs or the .pngs?

**Comment by martinheidegger** [comment]
The advantage of `pngs` over `svgs` is quicker rendering, the advantage of svgs over png might be sharpness on all levels.  I guess its your choice, but this issue can be closed for now.

**Comment by Tannybunny** [comment]
The following images are still blured/low resolution
![Screen Shot 2020-02-21 at 11 54 00](https://user-images.githubusercontent.com/51223963/75000320-60e04600-54a1-11ea-9441-14c70e78ea57.jpg)
:

The last one with the text is especially problematic since the blurry text is hard to read, I don't have the original file of this , @marcchataigner can you maybe export this as svg or send me the vector file?

I realized that the header illustration (umbrella martina) is an SVG but all the other files are png..?

**Comment by Torgian** [comment]
@Tannybunny While discussing with Martin, the images remained as PNGs due to faster rendering.  SVGs are sharper though, so I can swap all images out for the SVGs since they will remain sharper. 

I do recall making a source set for the how it works section, but it looks like it was overridden someplace. 

Also, I have all the svgs to make the swap. I can do this after lunch.

*EDIT* @Tannybunny the last image ( Backlog / In Progress ) is being replaced with[ HTML code ](https://github.com/consento-org/consento-website/pull/67)

**Comment by Torgian** [comment]
@Tannybunny I've replaced the pngs with svgs in the How It Works section. See [aa51b0eb](https://github.com/consento-org/consento-website/commit/aa51b0ebd6e3531f8cb84d87b19b5df54c5f77cc) You should be able to see it on the live website shortly.

I will write a new issue for the rest of the images, since this issue is specifically for the How It Works section.

**Comment by Tannybunny** [comment]
> @Tannybunny While discussing with Martin, the images remained as PNGs due to faster rendering. SVGs are sharper though, so I can swap all images out for the SVGs since they will remain sharper.

We also have the PNGs in different resolutions for different screens, does it make sense to use that ? I don't know what is better in terms of performance, but it would be nice to have sharp images :D now they look good

> EDIT @Tannybunny the last image ( Backlog / In Progress ) is being replaced with HTML code

the image of the two people swinging around needs to be an svg or high resolution png though, the image can be found in the repository its called human-centric.svg / human-centric1x.png etc

**Comment by Torgian** [comment]
@Tannybunny Refer to [f224f03](https://github.com/consento-org/consento-website/pull/67/commits/f224f0311b4eda5c2500bda6b2460e01b5667e00). I added a source set for that specific image in the PR. We can keep this issue open until the PR is merged.

**Comment by Torgian** [comment]
PR is merged. Closing.
