### ISSUE TITLE
Navigation Bar Logo Spacing 

### ISSUE THREAD

**Issue by Tannybunny** [consento-org/consento-website#22]
<img width="1211" alt="Screen Shot 2020-02-04 at 16 05 26 copy" src="https://user-images.githubusercontent.com/51223963/73722848-ce366c00-476a-11ea-92ff-0abc43bb1086.png">

In the current navigation bar the logo seems to be a bit off - there is more space to the bottom than to the top. Might this be due to some spacing issues in the logo.png ?

Same in the mobile version:
<img width="1059" alt="Screen Shot 2020-02-04 at 16 27 22 copy" src="https://user-images.githubusercontent.com/51223963/73723377-418cad80-476c-11ea-9fcf-623fd0664151.png">

Also, please remove the red border around the hamburger menu icon

**Comment by Tannybunny** [comment]
Also, why did you remove the fading of the navigation bar while scrolling ?

**Comment by Torgian** [comment]
> Also, why did you remove the fading of the navigation bar while scrolling ?

This is something that has actually changed twice: First, Marc suggested we reduce the size of the nabber when scrolling ( instead of it fading away ), and then Daniel did not like this. So I made a decision to keep the nav bar sticky on top; no special animations, no fading. 

We will keep it like this until other major issues are fixed. It's easy enough to change, but a decision needed to be made, so I made it.

**Comment by Torgian** [comment]
Fixed brand spacing

**Comment by Torgian** [comment]
border removed. I've kept default behavior so that on hover, the hamburger icon glows a very slight color.  I also made the bars slightly longer.

**Comment by Torgian** [comment]
In mobile view, after you click the hamburger icon, the menu shows. I added a little big of padding on the bottom of the menu to put a little space between the bottom of the download button and the bottom of the menu. Please check.

**Comment by Tannybunny** [comment]
At the moment it seems as if there is no additional space between the download button and the bottom?
@Torgian 
Also, after tapping the menu a redish background appears. The alignment of the logo and the menu icon seems a bit off too.  Here is a picture of what I think should be changed:

<img width="908" alt="Screen Shot 2020-02-14 at 11 13 11" src="https://user-images.githubusercontent.com/51223963/74495544-72fb3b00-4f1b-11ea-9ac2-f5cd5b02ae66.png">

**Comment by Torgian** [comment]
@Tannybunny Can you please look at this commit? [f35a5bd](https://github.com/consento-org/consento-website/commit/f35a5bde60e1878251baa3cd7eeddca8392a8cb4)

I added a top / bottom margin to the download button in mobile view. 

<img width="615" alt="Screen Shot 2020-02-17 at 9 49 17 AM" src="https://user-images.githubusercontent.com/8596793/74617988-e3e46200-516a-11ea-9107-2bc8b72616a8.png">
