### ISSUE TITLE
Navigation Bar Styling

### ISSUE THREAD

**Issue by Tannybunny** [consento-org/consento-website#23]
The current style with the grey background and dark grey border doesn't look so modern .. 
I suggest a white background and a very subtle shadow like this
`box-shadow: 0 0 4px #00000038;`
It also helps to indicate the navigation bar is on a different layer than the content / elevated 

like this:
<img width="1218" alt="Screen Shot 2020-02-04 at 16 11 38_menu" src="https://user-images.githubusercontent.com/51223963/73724349-7437a580-476e-11ea-8c81-8c34e4bf4c55.png">

**Comment by Torgian** [comment]
Good idea, I like this

**Comment by Torgian** [comment]
I've applied this styling and adjusted the box-shadow.
