### ISSUE TITLE
Top Page Layout, Image, Fonts

### ISSUE THREAD

**Issue by Tannybunny** [consento-org/consento-website#24]
<img width="1680" alt="Screen Shot 2020-02-04 at 17 02 46" src="https://user-images.githubusercontent.com/51223963/73725254-5cf9b780-4770-11ea-979b-053dd18a1420.png">

I made a suggestion for the top page. The illustration was uploaded into git ("privacy by design.png")
The button should be closer to the text - at the moment, there is a huge gap.

Also, as mentioned in #15 , the font system should be improved. The body needs more line height and the contrast between heading and body can be stronger, since we don't have so much text I'd suggest making the headings a bit bigger.

**Comment by Torgian** [comment]
Ok, will do. I had originally made the button farther to the bottom, since that was in Marc's original design ( I suppose it has changed now )

**Comment by Torgian** [comment]
So I have followed the font sizes on Marc's Zeppelin design and have also added the new images. Closing this issue.
