### ISSUE TITLE
HTML code for the roadmap

### ISSUE THREAD

**Issue by martinheidegger** [consento-org/consento-website#26]
Currently the roadmap is added as an image. It would be good if that were html code that can be copy/pasted and linked (maybe to github issues).

**Comment by Torgian** [comment]
Yeah, I like that idea. I'll work on this after other issues are resolved.

**Comment by martinheidegger** [comment]
The code coloring has been added in #59 but there is still an indentation issue.

**Comment by Torgian** [comment]
I have made the first prototype for the progress block [here](https://github.com/consento-org/consento-website/pull/67)

I replaced the image with the `human-centric` file, which is just two people hanging.
Below that I placed the backlog/progress blocks.

<img width="748" alt="Screen Shot 2020-02-18 at 4 20 08 PM" src="https://user-images.githubusercontent.com/8596793/74717306-23927300-526b-11ea-9a30-30f2dd48a37a.png">
<img width="729" alt="Screen Shot 2020-02-18 at 4 20 16 PM" src="https://user-images.githubusercontent.com/8596793/74717314-2725fa00-526b-11ea-88d9-c0e06cf436a3.png">

You can see that the blocks extend down past the paragraph text on the right side. 

@consento-org/design Please take a look at the prototype screenshot and tell me what you think needs to be changed. I feel like making the right side of the "Roadmap" block, where it says "Consento Roadmap" can be centered vertically, so that it sits in the middle of the column instead of the very top.

Also, please let me know what improvements you think can be made for the Backlog and In Progress blocks.

**Comment by marcchataigner-zz** [comment]
Yes, I agree. Thee `consento backlog` would be best aligned with `backlog` and `in progress` ideally.

**Comment by marcchataigner-zz** [comment]
Note though, for this 'MVP website', i wouldn't spend much time on linking this with git. it is a nice feature but I guess not fundamental yet. Maybe the website will change again in 6 months time...   :-)   Unless it is a good coding practice or exercise?

**Comment by Torgian** [comment]
> Yes, I agree. Thee `consento backlog` would be best aligned with `backlog` and `in progress` ideally.

This is just some quick work locally. How does something like this look? @marcchataigner 

<img width="1411" alt="Screen Shot 2020-02-19 at 9 26 15 AM" src="https://user-images.githubusercontent.com/8596793/74792993-f80a9980-52f9-11ea-9178-34493535c7c5.png">

**Comment by Torgian** [comment]
@marcchataigner @martinheidegger I'd like your feedback on the following proposed change.

In Progress is changed to Developing.
Here is a screenshot:

<img width="480" alt="Screen Shot 2020-02-19 at 7 00 33 PM" src="https://user-images.githubusercontent.com/8596793/74828536-3d56b780-534a-11ea-9bdf-015ba4505e93.png">

I feel like this looks cleaner. 

Also, we could also change the bottom border of "Backlog" into Consento red, while Developing remains Consento blue.

<img width="459" alt="Screen Shot 2020-02-19 at 7 07 47 PM" src="https://user-images.githubusercontent.com/8596793/74829055-29f81c00-534b-11ea-97dd-d1e888953307.png">

Changing the word "In Progress" to "Developing" isn't important, just an idea. Would like your feedback, thank you :)

**Comment by Torgian** [comment]
Refer to commit [322342](https://github.com/consento-org/consento-website/pull/67/commits/322342cce087d4f4b2c7af13d5d8e05a071c87b2)

Mobile:
<img width="333" alt="Screen Shot 2020-02-21 at 9 24 42 AM" src="https://user-images.githubusercontent.com/8596793/74995871-063cef00-548d-11ea-829e-c2bead497e6b.png"> 

<img width="322" alt="Screen Shot 2020-02-21 at 9 24 47 AM" src="https://user-images.githubusercontent.com/8596793/74995875-06d58580-548d-11ea-927e-5f41ea9923cb.png">


<img width="325" alt="Screen Shot 2020-02-21 at 9 24 37 AM" src="https://user-images.githubusercontent.com/8596793/74995865-0341fe80-548d-11ea-9642-13795c239596.png">

Ipads:

<img width="775" alt="Screen Shot 2020-02-21 at 9 25 19 AM" src="https://user-images.githubusercontent.com/8596793/74995912-210f6380-548d-11ea-8d5d-325b7d9cc6f6.png">
<img width="1025" alt="Screen Shot 2020-02-21 at 9 25 29 AM" src="https://user-images.githubusercontent.com/8596793/74995916-2371bd80-548d-11ea-81bd-7ed70796526f.png">

laptop / 4k

<img width="772" alt="Screen Shot 2020-02-21 at 9 25 59 AM" src="https://user-images.githubusercontent.com/8596793/74995932-2f5d7f80-548d-11ea-9260-6fc079056a53.png">
<img width="326" alt="Screen Shot 2020-02-21 at 9 26 28 AM" src="https://user-images.githubusercontent.com/8596793/74995935-31bfd980-548d-11ea-8114-a28911a13823.png">

**Comment by Torgian** [comment]
Reverted "Develop" back to in progress to match original design. Commit [here](https://github.com/consento-org/consento-website/pull/67/commits/969ea108d704b6e7e6dd6b47c517b5ac4db73cf3)

<img width="1076" alt="Screen Shot 2020-02-21 at 9 49 59 AM" src="https://user-images.githubusercontent.com/8596793/74996808-8a907180-548f-11ea-97ca-7276ce26891c.png">

**Comment by Torgian** [comment]
Adjusted bottom border color opacity. [Commit here](https://github.com/consento-org/consento-website/pull/67/commits/6120c39b3442980c80180a65d285a83a934dbd1f)

<img width="373" alt="Screen Shot 2020-02-21 at 9 54 49 AM" src="https://user-images.githubusercontent.com/8596793/74997115-549fbd00-5490-11ea-96fd-1d11598889f2.png">

**Comment by marcchataigner-zz** [comment]
Thanks a lot! It is a great idea to cut the image sot he mobile version size remains readable. 

- [x] Regarding the positioning, having the `consento` of `consento roadmap` middle-aligned with `backlog` & `In Progress` is great. so eve in tablet mode or middle size screens, there is still visually an alignment.  
- [x] Regarding the bar colour, I would put is in a grey tone, or just skip it even.

**Comment by Torgian** [comment]
This isn't 100% responsive, but tablet mode on iPad and such is good.  [commit ](https://github.com/consento-org/consento-website/commit/267a0723fd90fe90bca13d613555f088f11b818c)

Tablet:

<img width="773" alt="Screen Shot 2020-02-26 at 7 09 28 PM" src="https://user-images.githubusercontent.com/8596793/75339508-9f279c00-58cb-11ea-8a2e-bc46486c6d84.png">


Laptop:

<img width="996" alt="Screen Shot 2020-02-26 at 7 09 55 PM" src="https://user-images.githubusercontent.com/8596793/75339524-a51d7d00-58cb-11ea-9a67-9328bee65237.png">


Hi-def Laptop

<img width="409" alt="Screen Shot 2020-02-26 at 7 11 03 PM" src="https://user-images.githubusercontent.com/8596793/75339585-c2524b80-58cb-11ea-9433-29eff2d79bb1.png">

4k

<img width="270" alt="Screen Shot 2020-02-26 at 7 11 22 PM" src="https://user-images.githubusercontent.com/8596793/75339605-cc744a00-58cb-11ea-8477-36ddf6117d2b.png">
