### ISSUE TITLE
Funding text is too big

### ISSUE THREAD

**Issue by martinheidegger** [consento-org/consento-website#27]
The funding text in the footer is way too big, @Tannybunny what would be a good size?

<img width="938" alt="Screen Shot 2020-02-05 at 08 06 24" src="https://user-images.githubusercontent.com/914122/73812697-1617ca80-4821-11ea-98b8-e48d3ee1c8a6.png">

**Comment by Torgian** [comment]
This is a good point; I don’t know if there are any legal requirements for how big it needs to be. Otherwise, I suggest we reduce the font size. As of now, it’s similar to Marc’s design.

@Tannybunny @marcchataigner let me know what you decide

**Comment by martinheidegger** [comment]
@Torgian I have never seen a design that shows the text in this size, please add a link to it.

**Comment by Torgian** [comment]
https://app.zeplin.io/project/5e008395a3e2aa1c6777a029/screen/5e27f7337b308098ebf9254c

**Comment by Torgian** [comment]
The design calls for 21px for the font size. I think 15px might be a better size.

**Comment by Torgian** [comment]
This is font-size 16px. What do you think?

<img width="1188" alt="Screen Shot 2020-02-05 at 1 54 50 PM" src="https://user-images.githubusercontent.com/8596793/73814824-1d3dd900-481f-11ea-971c-9a008efada45.png">

**Comment by martinheidegger** [comment]
In the zepplin file, the link size/title size ratio is different, the title font is "Bold" not "ExtraBold" and the lineheight is very different, giving a more compact image.

<img width="1040" alt="Screen Shot 2020-02-05 at 14 59 37" src="https://user-images.githubusercontent.com/914122/73815056-28e1cd80-4828-11ea-9c19-c37e9c43a788.png">

**Comment by Torgian** [comment]
I will need to use a lighter Work Sans font then; WorkSans regular is too heavy; it looks like the footer should use Work Sans Light, although it's not specified. Otherwise, font size, weight and line height matches the document. I'll send a screenshot after I make the change locally.

**Comment by Torgian** [comment]
Unfortunately ( as seems to always be the case ) the styles from the Zeplin file don't seem to translate into the real world. 

Line spacing between the elements are too narrow. I'll need to take some time to add padding and test.

<img width="858" alt="Screen Shot 2020-02-05 at 2 25 50 PM" src="https://user-images.githubusercontent.com/8596793/73816410-87587d00-4823-11ea-83d6-4b2ec792b0e1.png">

**Comment by Torgian** [comment]
I've made some changes and pushed them to branch [fix-footer](https://github.com/consento-org/consento-website/tree/fix-footer)

You can review if you want, or I can merge into next.

**Comment by Torgian** [comment]
I went ahead and merged into the `next` branch. Please review and close / comment as needed.

**Comment by martinheidegger** [comment]
@torgian Screenshot and link to changes in commit please.

**Comment by Torgian** [comment]
I made a single change: See commit [40efa983](https://github.com/consento-org/consento-website/commit/40efa9838a84f855f39c2b3987456f2fa5c84519)

Screenshot shows the new footer letter spacing. The styling for font-size, line height, letter spacing, matches what is in the Zeplin design. 

I believe this issue is ready to close; please review. 

Current footer (from write.georepublic)

<img width="1516" alt="Screen Shot 2020-02-13 at 1 14 12 PM" src="https://user-images.githubusercontent.com/8596793/74403927-f35e6500-4e63-11ea-9985-ba9b263a2a8c.png">


Screenshot from Zeplin
<img width="960" alt="Screen Shot 2020-02-13 at 1 21 15 PM" src="https://user-images.githubusercontent.com/8596793/74403899-d164e280-4e63-11ea-8cff-a5e43d4ca854.png">

**Comment by martinheidegger** [comment]
It looks a bit weird in smaller modes, are the icons supposed to be vertically centered or aligned on top?  (it seems neither)

<img width="583" alt="Screen Shot 2020-02-13 at 15 33 23" src="https://user-images.githubusercontent.com/914122/74407864-3de8dd00-4e76-11ea-8971-e80deab1beb5.png">

**Comment by Torgian** [comment]
I suggest vertically centered on smaller resolutions, I think that might look better.

Or, alternatively, we can have them drop below the Funding Text; this might also make the funding text look better on tablet resolutions.

**Comment by Torgian** [comment]
Please see PR [here](https://github.com/consento-org/consento-website/pull/58)

**Comment by martinheidegger** [comment]
Closed in #58
