### ISSUE TITLE
Social icons are grey, should be white

### ISSUE THREAD

**Issue by martinheidegger** [consento-org/consento-website#28]
<img width="277" alt="Screen Shot 2020-02-05 at 14 10 39" src="https://user-images.githubusercontent.com/914122/73812769-50816780-4821-11ea-9403-fbbf8c470a27.png">

**Comment by Torgian** [comment]
Yes, in the original design they were grey in the top bar; it makes sense to change them to white since they are in the footer now.

**Comment by Torgian** [comment]
It looks like I made a mistake in the latest merge; the icon is too large. I will revert back to original size.

**Comment by martinheidegger** [comment]
Looks good.
