### ISSUE TITLE
The EU logo needs to have the correct size

### ISSUE THREAD

**Issue by martinheidegger** [consento-org/consento-website#29]
Currently the EU logo is square and not proportionally sized in comparison with the NGI ledger logo:

<img width="938" alt="Screen Shot 2020-02-05 at 08 06 24" src="https://user-images.githubusercontent.com/914122/73812814-80306f80-4821-11ea-9c70-f1619e0dc0bc.png">

The correct logo is seen here:

https://ec.europa.eu/inea/en/connecting-europe-facility/cef-energy/beneficiaries-info-point/publicity-guidelines-logos

(note: since we added the text in the middle we do not need to use the version of the logo with the text in the bottom)

**Comment by Torgian** [comment]
I have replaced the logo with the flag from your link. I don't think it needs any spacing fixes, but please check and comment / close as needed.

**Comment by Torgian** [comment]
Refer to commit [1d87515a](https://github.com/consento-org/consento-website/commit/1d87515a360cd291ca3cfea67cbd588aaf806603)

**Comment by martinheidegger** [comment]
Commented: https://github.com/consento-org/consento-website/commit/1d87515a360cd291ca3cfea67cbd588aaf806603

**Comment by Torgian** [comment]
Please see commits: [510cdf539](https://github.com/consento-org/consento-website/commit/510cdf539b5c3213cf78dc80dc70158bdaf58314) and [cfaa616](https://github.com/consento-org/consento-website/commit/cfaa6168296670115462cc9d7525486ae01d3dc2)

Replaced EU logo with an optimized PNG version. 

<img width="1246" alt="Screen Shot 2020-02-13 at 1 45 00 PM" src="https://user-images.githubusercontent.com/8596793/74405207-7c2ad000-4e67-11ea-8c5a-2926c3bbc696.png">

**Comment by martinheidegger** [comment]
LGTM
