### ISSUE TITLE
New Favicon

### ISSUE THREAD

**Issue by martinheidegger** [consento-org/consento-website#30]
The site still boasts a the old favicon.

<img width="103" alt="Screen Shot 2020-02-05 at 08 04 17" src="https://user-images.githubusercontent.com/914122/73812973-ff25a800-4821-11ea-8ec0-b21372ec64a0.png">

This is also true for other consento icons:

https://github.com/consento-org/consento-website/blob/80d86a885dc9a368dcdeed9f3c90cd1a2cfe5165/default.hbs#L13-L23

**Comment by Torgian** [comment]
Please refer to this [PR](https://github.com/consento-org/consento-website/pull/57)
