### ISSUE TITLE
No red-on-blue text

### ISSUE THREAD

**Issue by martinheidegger** [consento-org/consento-website#31]
The hover style of the links in the footer is hurting the eyes. This needs to look different.

@consento-org/design  do you have a nice proposal for this?

<img width="172" alt="Screen Shot 2020-02-05 at 14 18 03" src="https://user-images.githubusercontent.com/914122/73813114-5deb2180-4822-11ea-91b1-a391b5114f5f.png">

**Comment by Torgian** [comment]
I thought it was rather nice. :-)

Maybe changing opacity on hover would be best

**Comment by martinheidegger** [comment]
@Torgian Design theory to read up on:

([blog post explaining basics](https://fontbundles.net/blog/ask-a-font-creator-basic-color-theory))
> Some combinations, especially if they’re fully saturated, can be painful .... Nobody likes to look at blue on top of red, or red on top of blue.

([other, more technical blog post](https://www.designworkplan.com/read/signage-and-color-contrast))

**Comment by Torgian** [comment]
Changes made in [#2ef338256d - R102-R105](https://github.com/consento-org/consento-website/commit/2ef338256dd79c6f0cb29b3ec7ebe76cebd2083a#diff-118d07f8a4d64a925eda1e4f5bdc2f05R102-R105)

**Comment by martinheidegger** [comment]
Thank you, already a lot better. Thought I would like to leave the issue open as @consento-org/design has an improvement suggestion. As a different means of highlighting a link might be needed to distinguish clickable areas (the links), unclickable areas (the "Whitepaper pending" text) and regular text (funding note). Also I tend to be a stickler for keyboard navigation: the tab-focus is not really great at the moment: 

<img width="250" alt="Screen Shot 2020-02-06 at 00 11 05" src="https://user-images.githubusercontent.com/914122/73854037-2fe2fd00-4875-11ea-8f54-cfb8e28c2fe0.png">

**Comment by Torgian** [comment]
This is the current look for tab focusing:

<img width="1064" alt="Screen Shot 2020-02-13 at 2 37 49 PM" src="https://user-images.githubusercontent.com/8596793/74408164-a8961a80-4e6e-11ea-8ce6-dd8546e59ded.png">

Does this look ok with you @martinheidegger ?

**Comment by martinheidegger** [comment]
I tried to forward the question about if it looks good to the @consento-org/design team :)

**Comment by marcchataigner-zz** [comment]
Looks good to me  :-)  👍

**Comment by martinheidegger** [comment]
It's here again

**Comment by Torgian** [comment]
Refer this [commit](https://github.com/consento-org/consento-website/commit/e6f325d37d38db56dfafa4d4f06ee1b40f5a342f)

<img width="344" alt="Screen Shot 2020-02-20 at 2 26 02 PM" src="https://user-images.githubusercontent.com/8596793/74906782-f1108380-53ec-11ea-96df-62d0fde0011d.png">

Removed red color when hovering, and turns opacity to full instead. @consento-org/design Any thoughts on how to make hovering over the links better?

**Comment by marcchataigner-zz** [comment]
I leave it to @Tannybunny  For me it does the job.   :-)
