### ISSUE TITLE
Remove shadow when not scrolling from menu

### ISSUE THREAD

**Issue by martinheidegger** [consento-org/consento-website#33]
@consento-org/design  correct me if I am wrong, but as far as I understand the shadow below the menu should only be there when the site is not scrolled to top, right?

**Comment by Tannybunny** [comment]
Yes that was proposed

**Comment by Torgian** [comment]
Refer to commits: [1](https://github.com/consento-org/consento-website/commit/ca814152010c8e096ded46ac95315b8a56177f51) and [2](https://github.com/consento-org/consento-website/commit/4c35a4188a386ac362ac02530e3096875e878d8e)

@martinheidegger Please review.

**Comment by martinheidegger** [comment]
This looks okay to me. I added a note on how it may be improved but I leave it up to you if you want to do that or just close this issue.

**Comment by Torgian** [comment]
I implemented your suggestions in commit [41ceb](https://github.com/consento-org/consento-website/commit/4f1ceb9ce0c2f55eb88406604fda3b6a07951dc6)

**Comment by Torgian** [comment]
See this [commit](https://github.com/consento-org/consento-website/commit/d5678f03dc9ebfc5cab1545252d26bc631f2a550)

@martinheidegger I double checked the sass file and I couldn't find anything wrong with the indentation. They are all tab indented. I also implemented your suggestion with the javascript.

`toggle` is one of those functions that I know about, but never remember ( I always remember classList.add and .remove ). Thanks for the reminder! It makes things more simple.

**Comment by martinheidegger** [comment]
Cool. Closing this issue.
