### ISSUE TITLE
Proper code coloring

### ISSUE THREAD

**Issue by martinheidegger** [consento-org/consento-website#34]
@consento-org/design If you want for the "technology" section to look a little bit impressive we should really have proper code coloring and a link to the section in our repository.

@Torgian there are online tools that can render code pre-colored (no javascript runtime needed). Maybe they also come with a set of color palettes to choose from.

<img width="587" alt="Screen Shot 2020-02-05 at 14 31 51" src="https://user-images.githubusercontent.com/914122/73813887-c0ddb800-4824-11ea-8f45-9663f350be4e.png">

**Comment by Torgian** [comment]
Agreed, I'll take a look.

**Comment by Torgian** [comment]
See the [following PR](https://github.com/consento-org/consento-website/pull/59)

**Comment by Torgian** [comment]
Fixed code block indentation [here](https://github.com/consento-org/consento-website/commit/138cdb254c140f0c5a79abf804b21d1e4f50590a)
<img width="556" alt="Screen Shot 2020-02-18 at 10 11 57 AM" src="https://user-images.githubusercontent.com/8596793/74698068-8ff37f00-5237-11ea-86ce-5e29f5d94f69.png">

**Comment by martinheidegger** [comment]
@Torgian it still has a dangling line and maybe a 2 character indent might be better ;)

<img width="218" alt="Screen Shot 2020-02-18 at 11 20 47" src="https://user-images.githubusercontent.com/914122/74698332-c255aa00-5240-11ea-8404-f7584388d264.png">

**Comment by Torgian** [comment]
See this [commit](https://github.com/consento-org/consento-website/commit/dc1ce7116597abbb7d481158e8b844c579aeeb84)

Removed the dangling line and changed indentation.

<img width="554" alt="Screen Shot 2020-02-18 at 10 36 13 AM" src="https://user-images.githubusercontent.com/8596793/74699014-84558780-523a-11ea-85d3-ce60136e002e.png">

**Comment by martinheidegger** [comment]
Much better, the indentation of the comment is wrong, but at this point I am happy.

**Comment by Torgian** [comment]
Fixed the indentation for the comment [here](https://github.com/consento-org/consento-website/commit/ba938c56c002d7eb20e945fcc84b55ba04d35f58)
