### ISSUE TITLE
Avoid multiple lines in headlines above illustrations

### ISSUE THREAD

**Issue by martinheidegger** [consento-org/consento-website#35]
Depending on the screen resolution (but particularly on desktop) the titles above images
are wrapped and a second line can appear.

<img width="381" alt="Screen Shot 2020-02-05 at 07 59 45" src="https://user-images.githubusercontent.com/914122/73813941-eff42980-4824-11ea-826f-3d46d21cb065.png" >

This result in an uneven layout

<img width="1144" alt="Screen Shot 2020-02-05 at 14 37 42" src="https://user-images.githubusercontent.com/914122/73813998-1ade7d80-4825-11ea-98bf-73ee12fa993b.png">

Make sure that the font-size of the headline always aligns.

**Comment by Torgian** [comment]
Yes, this is an issue I've been trying to figure out, specifically for that forth image. Bootstrap grid layout (specifically col-md-3) are too narrow for the title of "Private network" to stay on one line, at least at this font size. 

Keeping this section in a 2x2 layout may be easier to deal with in this case, or perhaps reducing the font size. Unless you know of another method we can use?

**Comment by martinheidegger** [comment]
As the size of the box is always bound to the size of the content, I believe it is unavoidable to reduce the font size to fit the size of the illustration.

**Comment by Torgian** [comment]
I changed the font size to 27px. See this [commit](https://github.com/consento-org/consento-website/commit/ac851df69cde874f140820c6ec9ee0882302e0ed) This is the maximum font available that won't force the text to wrap in larger resolutions.

**Comment by Torgian** [comment]
<img width="1370" alt="Screen Shot 2020-02-14 at 4 42 00 PM" src="https://user-images.githubusercontent.com/8596793/74515191-0c8d1180-4f49-11ea-99f6-a46d016974ee.png">
<img width="827" alt="Screen Shot 2020-02-14 at 4 42 08 PM" src="https://user-images.githubusercontent.com/8596793/74515201-11ea5c00-4f49-11ea-8930-81a14dd2f422.png">
<img width="497" alt="Screen Shot 2020-02-14 at 4 42 25 PM" src="https://user-images.githubusercontent.com/8596793/74515206-13b41f80-4f49-11ea-8432-8c8583f9c5fb.png">

**Comment by martinheidegger** [comment]
LGTM.

**Comment by martinheidegger** [comment]
<img width="984" alt="Screen Shot 2020-02-18 at 15 43 03" src="https://user-images.githubusercontent.com/914122/74710616-69e4d380-5265-11ea-8475-6f294b9838fe.png">

If the screen size is smaller than 1200px it still breaks.

**Comment by Torgian** [comment]
Refer to [this commit](https://github.com/consento-org/consento-website/commit/0aa9a06e2e45be4f69a93ad24182e1bcb0e664a5)

Between 992px and 1200px, this is now fixed by reducing font size for the h3 element. 

<img width="990" alt="Screen Shot 2020-02-18 at 3 28 23 PM" src="https://user-images.githubusercontent.com/8596793/74713512-b16a6000-5263-11ea-8629-5cf26c6bcc70.png">
<img width="1178" alt="Screen Shot 2020-02-18 at 3 29 00 PM" src="https://user-images.githubusercontent.com/8596793/74713525-b8916e00-5263-11ea-8fe0-028a9112900b.png">
