### ISSUE TITLE
"Stay Updated" needs new target

### ISSUE THREAD

**Issue by martinheidegger** [consento-org/consento-website#37]
The link on the "Stay Updated" points to a `./mailform` which is not available when published to dat. We need another "mailinglist" signup formular.

**Comment by marcchataigner-zz** [comment]
@martinheidegger @Torgian I didn't know about this issue with DAT. 

I create this mailchimp sign up [page](https://mailchi.mp/54ed51f62b3d/consento-updates-signup).

so the button `stay updated` and `Be the first to use it` link in a new tab to: 

```
https://mailchi.mp/54ed51f62b3d/consento-updates-signup
```

**Comment by Torgian** [comment]
See commit [2cf1cfa](https://github.com/consento-org/consento-website/commit/2cf1cfa82a3360312928730767e377f89efbeb38)

**Comment by martinheidegger** [comment]
LGTM
