### ISSUE TITLE
Autor display in blog posts are blue

### ISSUE THREAD

**Issue by martinheidegger** [consento-org/consento-website#38]
On a blog article with authors, like on `./blog/funding-ngi-2019/`, the authors are displayed in blue:

<img width="749" alt="Screen Shot 2020-02-05 at 08 08 47" src="https://user-images.githubusercontent.com/914122/73814536-b7ede600-4826-11ea-8530-e6dc006687dc.png">

**Comment by martinheidegger** [comment]
@consento-org/design Can you send a quick layout for this?

**Comment by marcchataigner-zz** [comment]
https://github.com/consento-org/consento-website/issues/38#issuecomment-582251858 

you mean a design on white background?

**Comment by martinheidegger** [comment]
Yes, very simple

**Comment by marcchataigner-zz** [comment]
@martinheidegger @Torgian Just replying a bit late here, sorry. 

- [x] Let's have this `author` content display on the white background. With `work sans` font. 
- [ ] Let's bring this content to the `supporter` page, as in https://zpl.io/VDw9lA3  (Because we don't have link to the blog anymore)

**Comment by Torgian** [comment]
Refer to commit [82d5702](https://github.com/consento-org/consento-website/commit/82d5702babd6f96cd24de1a304607069a3e61a0e) for fix.

<img width="1255" alt="Screen Shot 2020-02-17 at 1 23 18 PM" src="https://user-images.githubusercontent.com/8596793/74625842-b0183500-5188-11ea-9559-6e3a4a3aeece.png">

**Comment by martinheidegger** [comment]
> Let's have this author content display on the white background. With work sans font.

The font is still wrong.

**Comment by Torgian** [comment]
The font is already WorkSans-Regular. Do you need it to be a different work-sans font? 

I did see that the font size and line height were being overridden by ghost styling. The following screenshot is with the base `p`aragraph settings ( 21px, line-height 27px, color rgba(0 0 0 0.87) )

<img width="797" alt="Screen Shot 2020-02-17 at 5 44 21 PM" src="https://user-images.githubusercontent.com/8596793/74642141-68f06b00-51ad-11ea-9744-ae06073fb772.png">

This is same settings, but using Worksans-Light 

<img width="454" alt="Screen Shot 2020-02-17 at 5 47 53 PM" src="https://user-images.githubusercontent.com/8596793/74642282-ace37000-51ad-11ea-8649-1a040c81ccd7.png">

And this is Worksans Medium: 

<img width="683" alt="Screen Shot 2020-02-17 at 5 48 50 PM" src="https://user-images.githubusercontent.com/8596793/74642377-d56b6a00-51ad-11ea-9831-5d4b0beb9471.png">

**Comment by marcchataigner-zz** [comment]
Great. I feel the Work sans Light is best, no? :-)

**Comment by Torgian** [comment]
Done. See this [commit](https://github.com/consento-org/consento-website/commit/827d2ae332de724a75133249a857dc5acb623097)

<img width="398" alt="Screen Shot 2020-02-17 at 6 48 14 PM" src="https://user-images.githubusercontent.com/8596793/74647200-3860ff00-51b6-11ea-8a3e-c489ba178aee.png">

**Comment by martinheidegger** [comment]
As far as I can see "AUTHOR" is still in the wrong don't.

**Comment by Torgian** [comment]
My mistake. 

Here is a screenshot using WorkSans-SemiBold
<img width="378" alt="Screen Shot 2020-02-18 at 9 10 58 AM" src="https://user-images.githubusercontent.com/8596793/74695376-bc56cd80-522e-11ea-962e-b2043e1f8f3b.png">

And this uses WorkSans Light

<img width="352" alt="Screen Shot 2020-02-18 at 9 14 03 AM" src="https://user-images.githubusercontent.com/8596793/74695499-2b342680-522f-11ea-8d10-c0361ee13680.png">


I think the SemiBold font looks better in this case. @marcchataigner @martinheidegger What do you think?

**Comment by martinheidegger** [comment]
As a design question: I like the semibold, but the description text font is too large, there should be between `5~10` words fitting in the block, not `3~6`

**Comment by Torgian** [comment]
This is a font size of 1.3em.

<img width="403" alt="Screen Shot 2020-02-18 at 10 24 22 AM" src="https://user-images.githubusercontent.com/8596793/74698475-e1e8d480-5238-11ea-9913-2f2b3c4bb027.png">

And this is with 1em.

<img width="370" alt="Screen Shot 2020-02-18 at 10 25 42 AM" src="https://user-images.githubusercontent.com/8596793/74698520-0fce1900-5239-11ea-8cd2-155cfa96eb9e.png">

**Comment by martinheidegger** [comment]
1em with 1.4em line-height, would be my choice.

**Comment by Torgian** [comment]
Refer to these commits for the [author box p](https://github.com/consento-org/consento-website/commit/ed8576a98fe500acfe73c2548b8469cc4d125815)  and [author box label](https://github.com/consento-org/consento-website/commit/fef86343a35c891aa8437bcc3ef6d29387f9bfbd) styling.

**Comment by Torgian** [comment]
Verified changes on live website:

<img width="900" alt="Screen Shot 2020-02-18 at 10 56 46 AM" src="https://user-images.githubusercontent.com/8596793/74700055-6dfcfb00-523d-11ea-8e14-697f61c972ab.png">

**Comment by martinheidegger** [comment]
LGTM
