### ISSUE TITLE
Link to Funding

### ISSUE THREAD

**Issue by martinheidegger** [consento-org/consento-website#39]
Like in the readme of the mobile app, the funding information should link to the funding program:

https://github.com/consento-org/mobile#funding

- EU: https://ec.europa.eu/info/
- Ledger: https://www.ngi.eu/about/ledger/
- H2020: https://ec.europa.eu/programmes/horizon2020/
- Project: https://cordis.europa.eu/project/id/825268

**Comment by Torgian** [comment]
Got it, thanks.

**Comment by marcchataigner-zz** [comment]
Thx @martinheidegger

**Comment by Torgian** [comment]
Please see following commit: [b18da55b](https://github.com/consento-org/consento-website/commit/b18da55b95a705b74bda8933a8f1b112408b3a4c)

The links were already added in an earlier commit. So, what needed to be done was change the colors for the `<a>` elements. I wasn't sure what would be good colors, so I referred to the color style [guide](https://app.zeplin.io/project/5e008395a3e2aa1c6777a029/screen/5e00854f87589c99923fcfb3) Marc had made earlier. 

Also, I made the font weight bold, for now. The following is a screen shot with one element in bold, the other not in bold. You can decide which is better.  The second screen shot is hover opacity and color.

Finally, the [EU](https://ec.europa.eu/info/) link is in the flag. I can add this to the footer text if you want. At the time I made the change earlier, I was following the text used [here](https://github.com/consento-org/mobile#funding)
<img width="974" alt="Screen Shot 2020-02-16 at 1 13 54 PM" src="https://user-images.githubusercontent.com/8596793/74599584-85ae7500-50bf-11ea-9ab4-33724af5195b.png">
<img width="849" alt="Screen Shot 2020-02-16 at 1 23 49 PM" src="https://user-images.githubusercontent.com/8596793/74599598-a676ca80-50bf-11ea-976b-0aa56dd6986c.png">

**Comment by martinheidegger** [comment]
Those colors are not okay. @consento-org/design

**Comment by Torgian** [comment]
@martinheidegger @consento-org/design How does this look? I checked out a color picker and went for a tetradic harmony. This is the color code: #5237c9

<img width="561" alt="Screen Shot 2020-02-17 at 5 33 54 PM" src="https://user-images.githubusercontent.com/8596793/74641185-d7342e00-51ab-11ea-829a-a3b3df6f9e8b.png">

**Comment by marcchataigner-zz** [comment]
Mmmhh. I sense that in the footer, the information should not catch too much attention. It should be there for those who look for it. If a really key info is in the footer, it means that we should place it elsewhere. What if the links are also white in color, but a font ‘medium’ for instance? Would that work?

**Comment by Torgian** [comment]
> Mmmhh. I sense that in the footer, the information should not catch too much attention. It should be there for those who look for it. If a really key info is in the footer, it means that we should place it elsewhere. What if the links are also white in color, but a font ‘medium’ for instance? Would that work?

Here is a screenshot with that in mind:

<img width="479" alt="Screen Shot 2020-02-17 at 6 56 19 PM" src="https://user-images.githubusercontent.com/8596793/74647761-3c415100-51b7-11ea-9526-94e5fa3c055e.png">

**Comment by Torgian** [comment]
@consento-org/design Is the above screenshot link style for the funding page acceptable?

**Comment by martinheidegger** [comment]
Should be alright.
