### ISSUE TITLE
Replace sidebar with top navigation bar

### ISSUE THREAD

**Issue by Torgian** [consento-org/consento-website#4]
Currently the sidebar seems ok on desktop, but on mobile it's troublesome. 

A couple of options would be to keep the sidebar on desktop, but replace it with a hamburger top bar on mobile. Or, completely replace it with a navigation top bar on desktop that turns into hamburger mode on mobile.

Related to PR 1

**Comment by Torgian** [comment]
Working on this now. Currently using a basic Bootstrap 4 top navigation bar that collapses into a hamburger style for mobile view. I think this is probably the best ( and simplest ) version we can go for.

**Comment by Torgian** [comment]
Merged into develop

**Comment by martinheidegger** [comment]
On the testserver?
