### ISSUE TITLE
Blog Menu Button

### ISSUE THREAD

**Issue by martinheidegger** [consento-org/consento-website#40]
The "Blog" button seems to have been dropped in the menu?

Next: 
<img width="436" alt="Screen Shot 2020-02-05 at 14 54 01" src="https://user-images.githubusercontent.com/914122/73814776-5ed28200-4827-11ea-9441-8eb31919312a.png">

Master:

<img width="144" alt="Screen Shot 2020-02-05 at 14 54 33" src="https://user-images.githubusercontent.com/914122/73814805-73af1580-4827-11ea-805f-784537fb1627.png">

**Comment by marcchataigner-zz** [comment]
@martinheidegger yes, we took it out for now, even if ghost is best for blogging.

We had only one blog post (that is moved below the `supporter` section - https://zpl.io/VDw9lA3 ). 

Let's first discuss about the content production strategy, have couple of posts to be published, and insert a blog entry there. What do you think?

**Comment by martinheidegger** [comment]
I was planning to write blog posts this and next week, so to me this is a bit bad timing.

**Comment by martinheidegger** [comment]
Quoting or off-channel conversation:

> As part of our documentation I am about to write several posts about our journey until here in the next two weeks. Topics are: "Why mobile first?", "Why we wrote the expo-export plugin?" "Challenges with the cryptography", "Design thoughts on the avatars", "How to join the consento effort", etc. On top of that we had a recent conversation with a journalist which might be published as well and I would like to ask a few outside contributions to be shown publicly as well.

I would be happy if we could-readd the "blog" button.

**Comment by Torgian** [comment]
This is done, but Blog page needs to be stylized. I made the changes within the admin page. Navigation bar may also need adjusting. 
Screenshots: 

<img width="1151" alt="Screen Shot 2020-02-16 at 1 31 24 PM" src="https://user-images.githubusercontent.com/8596793/74599682-dd011500-50c0-11ea-8aff-18e461aa19f6.png">
<img width="1168" alt="Screen Shot 2020-02-16 at 1 31 37 PM" src="https://user-images.githubusercontent.com/8596793/74599683-e1c5c900-50c0-11ea-8d70-4c8e6a178276.png">
<img width="1172" alt="Screen Shot 2020-02-16 at 1 31 46 PM" src="https://user-images.githubusercontent.com/8596793/74599684-e38f8c80-50c0-11ea-8262-4c2b3fba07d8.png">

**Comment by martinheidegger** [comment]
> Blog page needs to be stylized.
> Navigation bar may also need adjusting.

Please open two issues.
