### ISSUE TITLE
Quote has wrong font

### ISSUE THREAD

**Issue by martinheidegger** [consento-org/consento-website#41]
In the `./about` page we have a quote and it is rendered with the wrong/old font:

<img width="758" alt="Screen Shot 2020-02-05 at 14 56 49" src="https://user-images.githubusercontent.com/914122/73814927-c4bf0980-4827-11ea-8b79-f710b81829a1.png">

**Comment by martinheidegger** [comment]
Same applies to captions and li elements

<img width="755" alt="Screen Shot 2020-02-05 at 14 57 53" src="https://user-images.githubusercontent.com/914122/73814983-ee783080-4827-11ea-94f0-f396349b9250.png">
<img width="766" alt="Screen Shot 2020-02-05 at 14 57 44" src="https://user-images.githubusercontent.com/914122/73814990-f0da8a80-4827-11ea-82c7-fcebf69d44a2.png">

**Comment by Torgian** [comment]
Refer [commit 0034cee](https://github.com/consento-org/consento-website/commit/0034cee66f9eeef819c5d4456896b3839ed52376) @martinheidegger 

<img width="409" alt="Screen Shot 2020-02-20 at 2 02 57 PM" src="https://user-images.githubusercontent.com/8596793/74905745-f8825d80-53e9-11ea-9efd-cabfb4e9a769.png">
<img width="948" alt="Screen Shot 2020-02-20 at 2 02 49 PM" src="https://user-images.githubusercontent.com/8596793/74905756-fe783e80-53e9-11ea-9a48-523aa3d7d901.png">

<img width="943" alt="Screen Shot 2020-02-20 at 2 02 42 PM" src="https://user-images.githubusercontent.com/8596793/74905795-19e34980-53ea-11ea-9f3e-dd65a34c77f8.png">
