### ISSUE TITLE
Team icons overlap with text

### ISSUE THREAD

**Issue by martinheidegger** [consento-org/consento-website#44]
The icons displayed in the `./team` overlap with the surrounding text.

<img width="326" alt="Screen Shot 2020-02-05 at 15 28 41" src="https://user-images.githubusercontent.com/914122/73816563-431daa80-482c-11ea-85b9-efd390807969.png">

**Comment by marcchataigner-zz** [comment]
@martinheidegger I am not sure how to fix this. 
- Decrease the font size of 2pt? 
- increase line spacing? 
- Reduce icons size of 4 px.?

**Comment by martinheidegger** [comment]
Everything you mentioned could/should work We have further options thought:

* Remove the avatars
* Change the way the text is written. (i.e. that the avatars are display bigger in a list)

What way would you choose?

**Comment by Torgian** [comment]
To revisit this issue, this is how it currently looks. Is this acceptable, or should this be modified further?

<img width="948" alt="Screen Shot 2020-02-20 at 2 29 21 PM" src="https://user-images.githubusercontent.com/8596793/74906989-73994300-53ed-11ea-8e2e-0c494951bbe2.png">
