### ISSUE TITLE
Too big spacing on content pages

### ISSUE THREAD

**Issue by martinheidegger** [consento-org/consento-website#45]
There is an enormous amount of spacing on the content pages:

<img width="624" alt="Screen Shot 2020-02-05 at 15 29 47" src="https://user-images.githubusercontent.com/914122/73816602-66485a00-482c-11ea-86ad-eeedc0cd9146.png">

This needs to be better proportioned.

**Comment by Torgian** [comment]
Refer to this commit: [8f05b7ab](https://github.com/consento-org/consento-website/commit/8f05b7ab4de5b557eb57407bb3a475717b657b3d)

<img width="1436" alt="Screen Shot 2020-02-19 at 8 38 21 PM" src="https://user-images.githubusercontent.com/8596793/74835207-d2ac7880-5357-11ea-921e-af2209d31872.png">


Screenshot 2

<img width="1432" alt="Screen Shot 2020-02-19 at 8 38 33 PM" src="https://user-images.githubusercontent.com/8596793/74835218-d6d89600-5357-11ea-9cc2-493652ddc508.png">

**Comment by Torgian** [comment]
Refer to commit [9f481dc](https://github.com/consento-org/consento-website/commit/9f481dc1beb5f6226983ab46dbf590e85fe2973c) and [9c7bf1f](https://github.com/consento-org/consento-website/commit/9c7bf1f1c7a961cf45a1338aee26f86dd1921523)

These fix the margin with the h1 element and the image spacing in the Supporter page.

<img width="1148" alt="Screen Shot 2020-02-19 at 9 10 29 PM" src="https://user-images.githubusercontent.com/8596793/74837390-59fbeb00-535c-11ea-8db7-362565a54ffd.png">

**Comment by Torgian** [comment]
Team page screenshot:

<img width="904" alt="Screen Shot 2020-02-19 at 9 14 09 PM" src="https://user-images.githubusercontent.com/8596793/74837700-0c33b280-535d-11ea-97b8-a30df23a4942.png">


@marcchataigner @Tannybunny can you take a look and review please? Please tell me if the spacing for images is correct or not. You can view these pages on the live site right now.

**Comment by Torgian** [comment]
Refer to the following commits for the following fixes: @marcchataigner Please review, you can see it on the live site as well.

bootstrap containers [10ada90](https://github.com/consento-org/consento-website/commit/10ada902bee6ff6ecbcb3c9b2299457950554df6) 
Padding
[3e3ad0b](https://github.com/consento-org/consento-website/commit/3e3ad0bd00a25954bf6ffce213da560bc4727b14) 
Blog header spacing 
[2558e8f](https://github.com/consento-org/consento-website/commit/2558e8f0292546cd9655ae38800a954e210138e2)
Posts container
[c7e61facc](https://github.com/consento-org/consento-website/commit/c7e61facc99761fb22daabc4e66c7f0c576d067a)

<img width="1406" alt="Screen Shot 2020-02-20 at 1 29 38 PM" src="https://user-images.githubusercontent.com/8596793/74903839-287b3200-53e5-11ea-8c5a-c147f8ad4ebc.png">
<img width="1476" alt="Screen Shot 2020-02-20 at 1 29 54 PM" src="https://user-images.githubusercontent.com/8596793/74903846-2b762280-53e5-11ea-9ab1-ce4305b45b4d.png">
<img width="1430" alt="Screen Shot 2020-02-20 at 1 29 47 PM" src="https://user-images.githubusercontent.com/8596793/74903848-2ca74f80-53e5-11ea-9f05-3e2a6c626a64.png">
<img width="1446" alt="Screen Shot 2020-02-20 at 1 30 02 PM" src="https://user-images.githubusercontent.com/8596793/74903850-2d3fe600-53e5-11ea-8e0f-cac1a8ef9b34.png">

**Comment by Torgian** [comment]
Fixed in [30db37](https://github.com/consento-org/consento-website/commit/30db37aa64d94af72ed2df3a80b06440927bfb7b)

<img width="1023" alt="Screen Shot 2020-02-20 at 2 35 52 PM" src="https://user-images.githubusercontent.com/8596793/74907588-a2fc7f80-53ee-11ea-845d-54599ad31ff6.png">

**Comment by martinheidegger** [comment]
Its a start. :)
