### ISSUE TITLE
Weird double underline in content links

### ISSUE THREAD

**Issue by martinheidegger** [consento-org/consento-website#46]
The content links (here seen under `./supporters`) weirdly have two underlines: one dotted and one on roll-over. This should be rendered consistently.

<img width="216" alt="Screen Shot 2020-02-05 at 15 31 08" src="https://user-images.githubusercontent.com/914122/73816709-a6a7d800-482c-11ea-81a7-219e2ffed316.png">

**Comment by marcchataigner-zz** [comment]
- [ ] Drop the `in our blog post` link
- [ ] and rewrite as "Learn more about it by reading how consento receive funding by NGI."

**Comment by martinheidegger** [comment]
@marcchataigner I think you mistook the issue here: Any link written in ghost will result in links with this style. This issue is in regard to any link style in content, not the blog post links in particular.

**Comment by Torgian** [comment]
Refer to commit [9e998a](https://github.com/consento-org/consento-website/commit/9e998a40c33f366a71b337c110de6590f5a2b779)

I found that ghost's default in `typography.scss` was causing this issue. I removed that line. 

<img width="876" alt="Screen Shot 2020-02-18 at 6 02 36 PM" src="https://user-images.githubusercontent.com/8596793/74725465-e2a15b00-5278-11ea-94c7-bb0c45dc5600.png">
<img width="833" alt="Screen Shot 2020-02-18 at 6 02 40 PM" src="https://user-images.githubusercontent.com/8596793/74725484-e7660f00-5278-11ea-88ba-a5a888a35ccc.png">

**Comment by Torgian** [comment]
Closing since this issue ( double underline on hover ) is resolved in commit [9e998a](https://github.com/consento-org/consento-website/commit/9e998a40c33f366a71b337c110de6590f5a2b779)
