### ISSUE TITLE
Content Link color not in palette

### ISSUE THREAD

**Issue by martinheidegger** [consento-org/consento-website#47]
The color of links in the content seems to not be part of the color palette used in consento?! @consento-org/design - what do you think?

<img width="169" alt="Screen Shot 2020-02-05 at 15 32 43" src="https://user-images.githubusercontent.com/914122/73816791-d951d080-482c-11ea-92bc-e6dc52fb9466.png">

**Comment by marcchataigner-zz** [comment]
I'm fine with it  :-)  

More colors palette here #6
