### ISSUE TITLE
Credits icon missing

### ISSUE THREAD

**Issue by martinheidegger** [consento-org/consento-website#48]
The NGI icon in the credits is missing:

<img width="850" alt="Screen Shot 2020-02-05 at 15 33 52" src="https://user-images.githubusercontent.com/914122/73816852-fa1a2600-482c-11ea-9c0f-24ff23c4207b.png">

**Comment by Torgian** [comment]
Ahh, good catch. Thought I fixed this. 

On that note isn’t NGI and LEDGER the same link?

**Comment by martinheidegger** [comment]
The NGI is the parent organization of Ledger

- Ledger: https://ledgerproject.eu/
- NGI: https://www.ngi.eu/

**Comment by marcchataigner-zz** [comment]
Let's skip that one, cf. #49
