### ISSUE TITLE
Image and set not aligned in 'how it works" section

### ISSUE THREAD

**Issue by marcchataigner-zz** [consento-org/consento-website#55]
I don't know exactly if it my browser, but the how it works section items seems not aligned. 

For the 4 illustrations, could the titles / images / text be horizontally aligned? (like in the Values section). 
Or it is because that section is responsive 

![Screen Shot 2020-02-13 at 10 51 16](https://user-images.githubusercontent.com/3974900/74394002-ec792780-4e4e-11ea-858e-f5341011b947.png)

**Comment by Torgian** [comment]
This is due to responsiveness from bootstrap. This can be fixed by setting a fixed height, but there might be a better way. @martinheidegger any thoughts?

**Comment by martinheidegger** [comment]
This is related to font-size + space. Reduce the size of the font and it will fit :)

**Comment by Torgian** [comment]
Referring to the screenshots below, this section looks quite nice right now. Fixing the font size in commit [0aa9a06](https://github.com/consento-org/consento-website/commit/0aa9a06e2e45be4f69a93ad24182e1bcb0e664a5) has contributed to this.

@marcchataigner @martinheidegger What do you think? 

<img width="1413" alt="Screen Shot 2020-02-18 at 5 47 03 PM" src="https://user-images.githubusercontent.com/8596793/74724106-ba186180-5276-11ea-8437-6851a0bce947.png">


<img width="794" alt="Screen Shot 2020-02-18 at 5 46 29 PM" src="https://user-images.githubusercontent.com/8596793/74724094-b4bb1700-5276-11ea-96db-c50643965cf8.png">
