### ISSUE TITLE
Top shadow visible without scrolling

### ISSUE THREAD

**Issue by martinheidegger** [consento-org/consento-website#64]
When opening the website for the first time, without scrolling, the webpage shows the shadow bar below. 

<img width="735" alt="Screen Shot 2020-02-17 at 16 41 42" src="https://user-images.githubusercontent.com/914122/74633164-65a4b180-51a4-11ea-8e6c-86a527a0a44b.png">

https://github.com/consento-org/consento-website/blob/82d5702babd6f96cd24de1a304607069a3e61a0e/assets/main/js/topbar.js#L1-L5

The shadow toggle needs to be triggered both when the user scrolls, and on first load of the page.

**Comment by Torgian** [comment]
Refer to [this commit](https://github.com/consento-org/consento-website/commit/947af3b8933175b582e89eaf1ce090eba0970513)

How does it look? Tests good locally ( does not show shadow on nav bar on first load )

**Comment by Torgian** [comment]
Refer to commit [a74daf8](https://github.com/consento-org/consento-website/commit/a74daf8ed49e59e402d9cc4f87cee64efe5b122b)

**Comment by Torgian** [comment]
I made a change according to Martin's comment [here](https://github.com/consento-org/consento-website/commit/872881a79e8b16477065b2c037b56a1c518449c4)

**Comment by Torgian** [comment]
I changed the logic and did some console testing. Commit is [here](https://github.com/consento-org/consento-website/commit/82256366595dd0925548bf0dad2e33f7df7c7c46)

**Comment by Torgian** [comment]
Refactored. Please see [commit](https://github.com/consento-org/consento-website/commit/d7d9c57c20968f63fd35f3824e2fcd72a1f4d0d6) here.
