### ISSUE TITLE
Favicon.ico is still old

### ISSUE THREAD

**Issue by martinheidegger** [consento-org/consento-website#65]
The [`/assets/images/favicon.ico`](https://raw.githubusercontent.com/consento-org/consento-website/next/assets/images/favicon.ico) is still the old consento logo.

**Comment by Torgian** [comment]
This is the fav-icon that should be used:

`<link rel="icon" type="image/png" href="{{asset "images/logo-consento-small.png"}}" />`

Refer to [commit](https://github.com/consento-org/consento-website/commit/e703754699853f1f0623e45da003cbb51a4f2262) 

I swapped out the favicon.ico files here. Unless there is a different file being used to set the favicon though, I don't think this is currently being used.

**Comment by martinheidegger** [comment]
Older browsers (IE) and some systems still prefer a .ico as a favicon. Good that the icon is replaced, but it would be good to figure out if the icons are correctly used.
