### ISSUE TITLE
Replace png images with svgs

### ISSUE THREAD

**Issue by Torgian** [consento-org/consento-website#75]
Refer to #21 for short conversation with @Tannybunny . 

All the images that are pngs should be swapped out for SVGs to help with sharpness on all resolutions. The problem is that lower resolution images are blurry.

**Comment by Torgian** [comment]
@consento-org/design Do we have an image to replace the smartphone? 

<img width="1198" alt="Screen Shot 2020-02-21 at 1 38 14 PM" src="https://user-images.githubusercontent.com/8596793/75007276-90964a80-54af-11ea-875e-027e142f6b6d.png">

I only have the single .png file for the smartphone, and I think Martin wants to replace it with an android version anyway.

**Comment by Tannybunny** [comment]
Right, I can prepare a new image for that

**Comment by Torgian** [comment]
Closing since a new phone image has been added.
