### ISSUE TITLE
Bold is too heavy

### ISSUE THREAD

**Issue by martinheidegger** [consento-org/consento-website#80]
The bold font used in most of the content seems to be be the ExtraBold font when the SemiBold would would suffice.

---

<img width="229" alt="Screen Shot 2020-02-26 at 14 43 23" src="https://user-images.githubusercontent.com/914122/75315562-65906a00-58a6-11ea-9d36-062fb9e212a4.png" style="border: 1px solid black">

---

<img width="843" alt="Screen Shot 2020-02-26 at 14 43 17" src="https://user-images.githubusercontent.com/914122/75315565-675a2d80-58a6-11ea-9f6b-27e173ff2ad9.png">

---
<img width="379" alt="Screen Shot 2020-02-26 at 14 43 09" src="https://user-images.githubusercontent.com/914122/75315570-6923f100-58a6-11ea-8ee8-54455e4d8cb4.png">

**Comment by Torgian** [comment]
Refer to commit [87ece96](https://github.com/consento-org/consento-website/commit/87ece9697ebc9995afecc48231ca9394b0a7c9f9). Fixes bold styling by reducing to semi-bold. The styling underneath Daniel's team section uses a `p` element, so I need to take some time to see where else this declaration is affecting.

<img width="811" alt="Screen Shot 2020-02-26 at 4 21 06 PM" src="https://user-images.githubusercontent.com/8596793/75325686-341e9b00-58b4-11ea-9c84-ff6553d2298c.png">
<img width="347" alt="Screen Shot 2020-02-26 at 4 21 15 PM" src="https://user-images.githubusercontent.com/8596793/75325694-3680f500-58b4-11ea-9550-0358e99588f1.png">

**Comment by Torgian** [comment]
<img width="815" alt="Screen Shot 2020-02-26 at 6 58 18 PM" src="https://user-images.githubusercontent.com/8596793/75338636-02b0ca00-58ca-11ea-87bb-cd9ad38aa0cf.png">

Commit [here](https://github.com/consento-org/consento-website/commit/736bfce6da76cfa941e8155f2e8638a31674c71e)

**Comment by martinheidegger** [comment]
It is still heavy in the the blog subtitle: 
<img width="713" alt="Screen Shot 2020-02-26 at 20 57 06" src="https://user-images.githubusercontent.com/914122/75342878-9ee2cd00-58da-11ea-8c17-dc55757b554f.png">

**Comment by Torgian** [comment]
[Commit](https://github.com/consento-org/consento-website/commit/a347f84449bc88cc6ab2692265e32c9a88832e4a)

<img width="658" alt="Screen Shot 2020-02-26 at 8 12 22 PM" src="https://user-images.githubusercontent.com/8596793/75343864-52948e80-58d4-11ea-9c42-38a87cc82d89.png">
