### ISSUE TITLE
Add OpenCollective to icons & in the content

### ISSUE THREAD

**Issue by martinheidegger** [consento-org/consento-website#81]
Now that consento has an [open collective page](https://opencollective.com/consento), it would be good to add it to the bottom icons and as a section in the text. 

- [x] Define text for landing
- [x] Add link to the bottom

**Comment by marcchataigner-zz** [comment]
- [x] link: https://opencollective.com/consento#section-contribute
- [x] section title proposal: Support the initiative 
- [x] text proposal: Consento is an open initiative for the Next Generation Internet. Even if you are not a developer, you can be part of it by supporting the initiative on Open Collective.

**Comment by marcchataigner-zz** [comment]
Proposal of visual
- [ ]  ![Screen Shot 2020-02-26 at 15 51 13](https://user-images.githubusercontent.com/3974900/75319427-fcadef80-58af-11ea-9f62-f5c91f23ba87.png)

- [ ] ![Screen Shot 2020-02-26 at 15 51 42](https://user-images.githubusercontent.com/3974900/75319532-34b53280-58b0-11ea-8fb8-10f2f79322e2.png)

**Comment by Torgian** [comment]
I added the new section, but do not have an image with the Consento logo in the middle, so I used the diversity image.

See [](https://github.com/consento-org/consento-website/commit/f9ea05bbb2012a0469df77a15f08e844f794fe92)

<img width="1321" alt="Screen Shot 2020-02-26 at 7 33 49 PM" src="https://user-images.githubusercontent.com/8596793/75341421-5d005980-58cf-11ea-9a30-1d59e81d0ca9.png">
<img width="616" alt="Screen Shot 2020-02-26 at 7 34 34 PM" src="https://user-images.githubusercontent.com/8596793/75341434-62f63a80-58cf-11ea-9e48-bb7ff442878e.png">

**Comment by Torgian** [comment]
@marcchataigner Can you confirm if this is ok? The new section is on the live site.

**Comment by marcchataigner-zz** [comment]
@Torgian great, good idea for the image! 

- [x] I would just set the image size 50% pr 60% of its current size
- [x] Maybe write `support the consento initiative` in the title (what do you think?) 
- [x] what if the Open Collective link is a blue button instead, centred?

**Comment by Torgian** [comment]
<img width="1236" alt="Screen Shot 2020-02-26 at 9 21 42 PM" src="https://user-images.githubusercontent.com/8596793/75348531-01899800-58de-11ea-80b9-7ff163e4e550.png">

**Comment by Torgian** [comment]
@marcchataigner Pushed the change.

**Comment by marcchataigner-zz** [comment]
Good good good.   :-)  

Maybe just end the sentence with "... supporting the initiative on Open Collective." 

Does it work if the label on the button is "Go to Open Collective"? Or too long? 

But, whatever you implement, good to me.    👍

**Comment by Torgian** [comment]
Refer to [0d46f](https://github.com/consento-org/consento-website/commit/0d46f0caa6d6f49384c96e813c20a098149a043e)

<img width="513" alt="Screen Shot 2020-02-27 at 8 02 41 AM" src="https://user-images.githubusercontent.com/8596793/75399786-2c083f00-5938-11ea-88a2-8a7ed5fc9362.png">
