### ISSUE TITLE
First image cut-off on < 1200px

### ISSUE THREAD

**Issue by martinheidegger** [consento-org/consento-website#84]
When the site is <1200px the first image gets cut-off on the main page.

<img width="921" alt="Screen Shot 2020-02-26 at 20 53 03" src="https://user-images.githubusercontent.com/914122/75342983-d81b3d00-58da-11ea-8fed-e4d07aa4ecf4.png">

**Comment by Torgian** [comment]
[Commit here](https://github.com/consento-org/consento-website/commit/0d0f0106b77454b040449d1037ce86352d1edb30) Fixes this under 1200px.
