### ISSUE TITLE
Roadmap break should occur ealier

### ISSUE THREAD

**Issue by martinheidegger** [consento-org/consento-website#85]
The roadmap block is turned from horizontal

---

<img width="359" alt="Screen Shot 2020-02-26 at 21 08 01" src="https://user-images.githubusercontent.com/914122/75343561-1cf3a380-58dc-11ea-86cf-109f5510d284.png">

---

to vertical at <576px

---

<img width="516" alt="Screen Shot 2020-02-26 at 21 09 16" src="https://user-images.githubusercontent.com/914122/75343677-51fff600-58dc-11ea-9eda-856ba5b187e1.png">

---

between <768 and >= 576 pixels it is set to the awkward size of:

---

<img width="531" alt="Screen Shot 2020-02-26 at 21 06 57" src="https://user-images.githubusercontent.com/914122/75343516-ff263e80-58db-11ea-9735-c45a44d77826.png">

---

maybe better if the blocks would be turned to vertical at <768

**Comment by Torgian** [comment]
I've got a fix, but will need to work on this moree tomorrow.

**Comment by Torgian** [comment]
See [commit](https://github.com/consento-org/consento-website/commit/c27743f0653813aa2c65c2973a051e284a4c3a8e)

Breaks into single / dual column mode in awkward resolutions
<img width="850" alt="Screen Shot 2020-02-26 at 9 11 25 PM" src="https://user-images.githubusercontent.com/8596793/75347869-b6bb5080-58dc-11ea-94a9-e58be6311757.png">
