### ISSUE TITLE
<p> size and line height 

### ISSUE THREAD

**Issue by Tannybunny** [consento-org/consento-website#89]
Looking through the long texts on the website I realized the body text needs adjustment. 
I suggest making it overall a bit smaller and increasing the line height for better readability of long text.
I found this might be suitable:
    font-size: 1.4em;
    line-height: 1.6em;

![font size and line height](https://user-images.githubusercontent.com/51223963/75416583-f4b68400-5971-11ea-9b01-d5d70cce9efd.jpg)

**Comment by Torgian** [comment]
Refer to [1ae76ca](https://github.com/consento-org/consento-website/commit/1ae76cae942c519d909ed23d477b5018fc15e5f4)

This changes the paragraph element to your specifications. Note this affects the home page as well, not just blog posts. However, this does not affect the footer text. 

The above push is live on the website now, so you can review it there too. 

<img width="904" alt="Screen Shot 2020-03-03 at 10 28 44 AM" src="https://user-images.githubusercontent.com/8596793/75737237-36f91000-5d3a-11ea-8e09-4588db0fbe5a.png">
<img width="553" alt="Screen Shot 2020-03-03 at 10 29 39 AM" src="https://user-images.githubusercontent.com/8596793/75737246-3a8c9700-5d3a-11ea-9a6f-c5d423d857f6.png">

Do you want the footer text to match the rest of the style? Below are screenshots with and without your new changes.

<img width="1250" alt="Screen Shot 2020-03-03 at 10 28 36 AM" src="https://user-images.githubusercontent.com/8596793/75737273-49734980-5d3a-11ea-99ed-1a714e6072ab.png">

With change:

<img width="1095" alt="Screen Shot 2020-03-03 at 10 34 11 AM" src="https://user-images.githubusercontent.com/8596793/75737377-8e977b80-5d3a-11ea-9471-0a8eeb3b0e3a.png">


@Tannybunny Please review

**Comment by Tannybunny** [comment]
I think overall it looks good, at least better :D I guess it's good to also apply it to the funding text, to distinguish it further from the footer links.
There are some spacing issues though between "p" and "h2" .. should I open a separate issue for that?

**Comment by Torgian** [comment]
Modified footer text here: https://github.com/consento-org/consento-website/commit/d7de4ac58fafc89058ab5ef1e1a6b98bfcb19bcc
