### ISSUE TITLE
minor styling issues

### ISSUE THREAD

**Issue by Torgian** [consento-org/consento-website#9]
There are some minor styling issues on the home page. Spacing is incorrect in How It Works. Also, the Team, About, and Support pages need to be modified, but these are dynamically created by Ghost's pages.

**Comment by marcchataigner-zz** [comment]
- [ ] link to form > opens in new tab
- [ ] link to Mailchimp contact form > opens in a new tab
- [ ] top navbar. Is it possible to add a 'dowload' Call-To-Action?
- [ ] top navbar. It disapears when scrolling down. Could it simply shrink and always stay? (you may have been discussing with Tanja about that alred, sorry)
- [ ] main page, the Call-To-Action hoover is a bit scary with the red on bleu  > text turns white ? 
- [ ] hero > could the text be align on the left on desktop? And on mobile center.
- [ ] fonts on Safari and Firefox don't appear as on Chrome
- [ ] spacing > IMG the phone is 20% too big
- [ ] spacing > add a break space before 'technology' 
- [ ] spacing > add a break space before 'how does it works'
- [ ] for the 'how it works' on mobile version > image & text centered (like values)
- [ ] Port Parallele logo <> NGI logo are interchanged 
- [ ] Footer. Add gutter (50px?) on the left
- [ ] About page - space between paragraphs + before first paragraph
- [ ] About page - the TITLE of the page is covered by navbar
- [ ] About page - Footer in blue + 50px gutter on left
- [ ] Team page - idem
- [ ] Supporter page - idem
- [ ] Credit page - missing
- [ ] Footer - maybe skip the "blog" link for now? 
- [ ] Contact - send mailto:, can it automatially set up the 'object' of the mail?

**Comment by Torgian** [comment]
> * [x]  link to form > opens in new tab
> * [x]  link to Mailchimp contact form > opens in a new tab
> * [x]  top navbar. Is it possible to add a 'dowload' Call-To-Action?
> * [x]  top navbar. It disapears when scrolling down. Could it simply shrink and always stay? (you may have been discussing with Tanja about that alred, sorry)
> * [x]  main page, the Call-To-Action hoover is a bit scary with the red on bleu  > text turns white ?
> * [x]  hero > could the text be align on the left on desktop? And on mobile center.
> * [x]  fonts on Safari and Firefox don't appear as on Chrome
> * [x]  spacing > IMG the phone is 20% too big

> * [x]  spacing > add a break space before 'technology'
> * [x]  spacing > add a break space before 'how does it works'
Fro the break space for the two issues above, I did so, but not sure if it's satisfactory. Please check.

> * [x]  for the 'how it works' on mobile version > image & text centered (like values)
  I've made the text centered on mobile and left aligned on desktop. Please let me know if this is good for you.

> * [x]  Port Parallele logo <> NGI logo are interchanged
> * [x]  Footer. Add gutter (50px?) on the left
> * [x]  About page - space between paragraphs + before first paragraph
> * [x]  About page - the TITLE of the page is covered by navbar
> * [x]  About page - Footer in blue + 50px gutter on left
> * [x]  Team page - idem
> * [x]  Supporter page - idem
> * [x]  Credit page - missing
> * [x]  Footer - maybe skip the "blog" link for now?
> * [x]  Contact - send mailto:, can it automatially set up the 'object' of the mail?
     For contact, do you mean subject?

**Comment by Torgian** [comment]
For the Credit page, we can either make a page locally, or use the ghost admin page to make it.
