### ISSUE TITLE
Privacy Policy 

### ISSUE THREAD

**Issue by dkastl** [consento-org/consento-website#91]
I think our website is missing some legal required information like Privacy Policy.

**Comment by martinheidegger** [comment]
Added privacy policy link in 67cb7ec55a630a4fc8b45101a4dfb71a78ad438d

**Comment by dkastl** [comment]
The link on the website does not point to the privacy policy.

**Comment by martinheidegger** [comment]
Very interesting issue. I can not replicate this issue locally. Needs investigation.

**Comment by martinheidegger** [comment]
Fixed with 1.1.2 release of dat-ssg
