### ISSUE TITLE
Open Collective widget

### ISSUE THREAD

**Issue by dkastl** [consento-org/consento-website#93]
We could an Open Collective Donate widget as described in their docs:
https://docs.opencollective.com/help/collectives/widgets

**Comment by dkastl** [comment]
@marcchataigner , not sure where this would make sense

**Comment by marcchataigner-zz** [comment]
yes, maybe for a start we could just change the current `go to open collective` by a `Donate to our collective` ?   

For a start, there will be not much donors or backers, so not much else to display.

![Screen Shot 2020-03-02 at 11 47 18](https://user-images.githubusercontent.com/3974900/75641510-d4d9d580-5c7b-11ea-9248-61b3b9fd33b5.png)


```
<a href="https://opencollective.com/webpack/donate" target="https://opencollective.com/consento#section-contribute">
  <img src="https://opencollective.com/webpack/donate/button@2x.png?color=blue" width=300 />
</a>
```

**Comment by martinheidegger** [comment]
Added this to the supporter page: 
<img width="843" alt="Screen Shot 2020-03-05 at 01 28 18" src="https://user-images.githubusercontent.com/914122/75900740-bc86d800-5e80-11ea-8ad3-98e947ebcc6f.png">
