### ISSUE TITLE
Content width of about, team and supporters pages

### ISSUE THREAD

**Issue by Tannybunny** [consento-org/consento-website#95]
The content of the about, team and supporters pages should be a bit smaller. I suggest to use the same width for the text as for the blog posts, it will make the text more pleasant for the eye. 👁

**Comment by Torgian** [comment]
Refer to https://github.com/consento-org/consento-website/commit/2d60b9d6727b8e6c6da0322c4872a328abfa9dfd

<img width="1141" alt="Screen Shot 2020-03-03 at 11 11 21 AM" src="https://user-images.githubusercontent.com/8596793/75739516-0320e900-5d40-11ea-87fc-a2c89b71ecad.png">
