### ISSUE TITLE
Mobile view align text to the left 

### ISSUE THREAD

**Issue by Tannybunny** [consento-org/consento-website#97]
Text that is longer than a few words should be aligned to the left. In the case of icons and "how it works" we should keep it centered, but the short passages should be aligned to the left if it's possible to define two different behaviours. For mobile the "p" font size could actually be a bit smaller, but if it's quite some work to implement this, we can keep the current size but still align it to the left 

![Screenshot_20200303-115810 copy](https://user-images.githubusercontent.com/51223963/75747042-43439400-5d5f-11ea-85bb-9f31b8de5f46.png)

**Comment by Torgian** [comment]
@Tannybunny I did as you asked for longer text elements in the home page, and also reduced the `p` element font size to 18px for the mobile size. 

For a few sections with shorter lengths of text, I did not change. Can you review please? Here are a couple of screen shots, but it should be on the live website whenever it updates.

<img width="497" alt="Screen Shot 2020-03-04 at 11 21 27 AM" src="https://user-images.githubusercontent.com/8596793/75842102-6f681f00-5e0a-11ea-8422-e88aed5cf3f9.png">
<img width="493" alt="Screen Shot 2020-03-04 at 11 21 43 AM" src="https://user-images.githubusercontent.com/8596793/75842105-72630f80-5e0a-11ea-80a9-487f89654a36.png">

**Comment by Torgian** [comment]
In the interest of realigning text, I've changed the text alignment for the larger views for 'Our Solution'. Commit here: https://github.com/consento-org/consento-website/commit/86aa81e408aafb1143060e2c972ee1c42b52e6d3

Screenshots of new view:

<img width="1449" alt="Screen Shot 2020-03-04 at 12 37 29 PM" src="https://user-images.githubusercontent.com/8596793/75845739-0639d900-5e15-11ea-8988-aa81ca6fe0e0.png">
<img width="331" alt="Screen Shot 2020-03-04 at 12 37 59 PM" src="https://user-images.githubusercontent.com/8596793/75845745-0a65f680-5e15-11ea-89aa-685d3090ee0b.png">
<img width="342" alt="Screen Shot 2020-03-04 at 12 38 05 PM" src="https://user-images.githubusercontent.com/8596793/75845747-0b972380-5e15-11ea-8a50-db9e16862eff.png">

**Comment by Torgian** [comment]
Due to some earlier changes, I had to change the image sizes / margins in tablet views. See https://github.com/consento-org/consento-website/commit/2d275c827d0b3a60476edbfea328b46617bd262b

Screen:

<img width="711" alt="Screen Shot 2020-03-04 at 12 46 38 PM" src="https://user-images.githubusercontent.com/8596793/75846194-83b21900-5e16-11ea-80de-390c3c599f84.png">

**Comment by Tannybunny** [comment]
The left aligned text is good. But on mobile all h2 are very small now, but it looks weird compared to  h3 etc. For example "our values" is relatively small compared to "privacy by design" , which is weird because it should be the other way around.
