### ISSUE TITLE
Rearrange Consento Roadmap elements

### ISSUE THREAD

**Issue by Tannybunny** [consento-org/consento-website#99]
I suggest to make the Roadmap section more coherent with the other sections, by rearranging some elements a bit. I would use "consento roadmap" as a centered headline just like with the other content. 
The illustration should be centered below that. (there is also a new version of that illustration, see #94 , but that will probably update automatically once the branche is merged)

<img width="790" alt="Screen Shot 2020-03-03 at 13 21 13 copy" src="https://user-images.githubusercontent.com/51223963/75753218-a805eb00-5d6d-11ea-9a8d-91d7a94aa7a1.png">

**Comment by Torgian** [comment]
@Tannybunny I made some changes and pushed them. Here are some screenshots.

Large screen: 

<img width="1471" alt="Screen Shot 2020-03-04 at 10 53 29 AM" src="https://user-images.githubusercontent.com/8596793/75840928-75103580-5e07-11ea-9e20-416216e46d84.png">

Mobile:

<img width="468" alt="Screen Shot 2020-03-04 at 10 45 45 AM" src="https://user-images.githubusercontent.com/8596793/75840951-80636100-5e07-11ea-969c-562460129dcc.png">


Tablet / awkward zones:

<img width="759" alt="Screen Shot 2020-03-04 at 10 45 28 AM" src="https://user-images.githubusercontent.com/8596793/75840975-9113d700-5e07-11ea-89e8-11108c5d1109.png">

<img width="751" alt="Screen Shot 2020-03-04 at 10 45 33 AM" src="https://user-images.githubusercontent.com/8596793/75840981-94a75e00-5e07-11ea-825f-e11c979bb63c.png">

**Comment by Tannybunny** [comment]
lgtm
